export const languages = [
  "Afrikaans",
  "Amharic",
  "Bulgarian",
  "Catalan",
  "Chinese (Hong Kong)",
  "Chinese (PRC)",
  "Chinese (Taiwan)",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English (UK)",
  "English (US)",
  "Estonian",
  "Filipino",
  "Finnish",
  "French (Canada)",
  "French (France)",
  "German",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Latvian",
  "Lithuanian",
  "Malay",
  "Norwegian",
  "Polish",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish (Latin America)",
  "Spanish (Spain)",
  "Swahili",
  "Swedish",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Vietnamese",
  "Zulu",
];